import { injectable, inject } from "tsyringe";
import { TOKENS } from "../../infrastructure/container";
import type { 
  IInventoryRepository, 
  ICardTemplateRepository 
} from "@/lib/domain/repositories/inventory.repository";
import { scryfall } from "@/lib/scryfall";
import type { ScryfallCard } from "@/lib/types/scryfall";
import { getTenantId } from "../../tenant-context";
import { IUseCase } from "./use-case.interface";
import { Game } from "@prisma/client";

export interface BulkInventoryItemRequest {
  scryfallId: string;
  price: number;
  quantity: number;
  condition: string;
  language: string;
  extras?: string[];
}

export interface AddBulkInventoryRequest extends Array<BulkInventoryItemRequest> {}

export interface BulkInventoryResult {
  cardName: string;
  status: "success" | "error";
  error?: string;
}

export interface AddBulkInventoryResponse extends Array<BulkInventoryResult> {}

@injectable()
export class AddBulkInventoryUseCase implements IUseCase<AddBulkInventoryRequest, AddBulkInventoryResponse> {
  constructor(
    @inject(TOKENS.InventoryRepository) private inventoryRepo: IInventoryRepository,
    @inject(TOKENS.CardTemplateRepository) private templateRepo: ICardTemplateRepository
  ) {}

  async execute(request: AddBulkInventoryRequest): Promise<AddBulkInventoryResponse> {
    const tenantId = getTenantId();
    if (!tenantId) throw new Error("Tenant context not found");

    const results: AddBulkInventoryResponse = [];
    const uniqueScryfallIds = Array.from(new Set(request.map(i => i.scryfallId)));

    // 1. Fetch existing templates
    const existingTemplates = await this.templateRepo.findByIds(uniqueScryfallIds);
    const existingTemplateIds = new Set(existingTemplates.map(t => t.id));
    const nameMap = new Map<string, string>();
    existingTemplates.forEach(t => nameMap.set(t.id, t.name));

    const missingIds = uniqueScryfallIds.filter(id => !existingTemplateIds.has(id));

    // 2. Fetch missing templates from Scryfall in bulk
    if (missingIds.length > 0) {
      const scryfallIdentifiers = missingIds.map(id => ({ id }));
      const scryfallCards = await scryfall.getCardsCollection(scryfallIdentifiers) as ScryfallCard[];
      
      const newTemplates = scryfallCards.map(card => {
        const imageUris = card.image_uris;
        return {
          id: card.id,
          name: card.name,
          set: card.set.toUpperCase(),
          imageUrl:
            imageUris?.normal ||
            imageUris?.large ||
            imageUris?.png ||
            card.card_faces?.[0]?.image_uris?.normal ||
            null,
          backImageUrl:
            card.card_faces?.[1]?.image_uris?.normal || null,
          game: Game.MAGIC,
          metadata: card as unknown as Record<string, unknown>,
        };
      });

      if (newTemplates.length > 0) {
        await this.templateRepo.createMany(newTemplates);
        newTemplates.forEach(t => nameMap.set(t.id, t.name));
      }
    }

    // 3. Fetch all relevant inventory items for these templates and tenant
    const existingInventoryItems = await this.inventoryRepo.findManyByTemplates(uniqueScryfallIds, tenantId);

    // Create a lookup key for inventory items
    const getInventoryKey = (item: { cardTemplateId: string, condition: string, language: string, extras: string[] }) => 
      `${item.cardTemplateId}|${item.condition}|${item.language}|${[...(item.extras || [])].sort().join(",")}`;

    const inventoryLookup = new Map<string, typeof existingInventoryItems[0]>();
    existingInventoryItems.forEach(item => {
      inventoryLookup.set(getInventoryKey(item), item);
    });

    // 4. Group items into updates and creates
    const itemsToCreate: Parameters<IInventoryRepository["createMany"]>[0] = [];
    const updatePromises: Promise<any>[] = [];

    for (const itemRequest of request) {
      const cardName = nameMap.get(itemRequest.scryfallId);
      if (!cardName) {
        results.push({
          cardName: itemRequest.scryfallId,
          status: "error",
          error: "Card not found"
        });
        continue;
      }

      const key = getInventoryKey({
        cardTemplateId: itemRequest.scryfallId,
        condition: itemRequest.condition,
        language: itemRequest.language,
        extras: itemRequest.extras || []
      });

      const existing = inventoryLookup.get(key);

      if (existing) {
        // Prepare update
        updatePromises.push(
          this.inventoryRepo.update(existing.id, {
            quantity: existing.quantity + itemRequest.quantity,
            active: true
          })
        );
      } else {
        // Prepare create
        itemsToCreate.push({
          id: "", // Generated by DB
          tenantId,
          cardTemplateId: itemRequest.scryfallId,
          price: itemRequest.price,
          quantity: itemRequest.quantity,
          condition: itemRequest.condition,
          language: itemRequest.language,
          active: true,
          extras: itemRequest.extras || []
        });
      }

      results.push({
        cardName,
        status: "success"
      });
    }

    // 5. Execute creations and updates
    await Promise.all([
      itemsToCreate.length > 0 ? this.inventoryRepo.createMany(itemsToCreate) : Promise.resolve(),
      ...updatePromises
    ]);

    return results;
  }
}
