import { injectable, inject } from "tsyringe";
import { TOKENS } from "../../infrastructure/tokens";
import type { 
  IInventoryRepository, 
} from "@/lib/domain/repositories/inventory.repository";
import { getTenantId } from "../../tenant-context";
import { IUseCase } from "./use-case.interface";
import { Game } from "@prisma/client";
import { CardTemplateService } from "../../domain/services/card-template.service";
import { domainEvents, DOMAIN_EVENTS } from "../../domain/events/domain-events";

export interface BulkInventoryItemRequest {
  scryfallId: string;
  price: number;
  quantity: number;
  condition: string;
  language: string;
  extras?: string[];
}

export type AddBulkInventoryRequest = BulkInventoryItemRequest[];

export interface BulkInventoryResult {
  cardName: string;
  status: "success" | "error";
  error?: string;
}

export type AddBulkInventoryResponse = BulkInventoryResult[];

@injectable()
export class AddBulkInventoryUseCase implements IUseCase<AddBulkInventoryRequest, AddBulkInventoryResponse> {
  constructor(
    @inject(TOKENS.InventoryRepository) private inventoryRepo: IInventoryRepository,
    @inject(TOKENS.CardTemplateService) private templateService: CardTemplateService
  ) {}

  async execute(request: AddBulkInventoryRequest): Promise<AddBulkInventoryResponse> {
    const tenantId = getTenantId();
    if (!tenantId) throw new Error("Tenant context not found");

    const results: AddBulkInventoryResponse = [];
    const uniqueScryfallIds = Array.from(new Set(request.map(i => i.scryfallId)));

    // 1. Resolve templates using the new service
    const resolvedTemplates = await this.templateService.resolveTemplates(uniqueScryfallIds);
    const nameMap = new Map<string, string>();
    resolvedTemplates.forEach(t => nameMap.set(t.id, t.name));

    // 3. Fetch all relevant inventory items for these templates and tenant
    const existingInventoryItems = await this.inventoryRepo.findManyByTemplates(uniqueScryfallIds, tenantId);

    // Create a lookup key for inventory items
    const getInventoryKey = (item: { cardTemplateId: string, condition: string, language: string, extras: string[] }) => 
      `${item.cardTemplateId}|${item.condition}|${item.language}|${[...(item.extras || [])].sort().join(",")}`;

    const inventoryLookup = new Map<string, typeof existingInventoryItems[0]>();
    existingInventoryItems.forEach(item => {
      inventoryLookup.set(getInventoryKey(item), item);
    });

    // 4. Group items into updates and creates
    const itemsToCreate: Parameters<IInventoryRepository["createMany"]>[0] = [];
    const updatePromises: Promise<unknown>[] = [];

    for (const itemRequest of request) {
      const cardName = nameMap.get(itemRequest.scryfallId);
      if (!cardName) {
        results.push({
          cardName: itemRequest.scryfallId,
          status: "error",
          error: "Card not found"
        });
        continue;
      }

      const key = getInventoryKey({
        cardTemplateId: itemRequest.scryfallId,
        condition: itemRequest.condition,
        language: itemRequest.language,
        extras: itemRequest.extras || []
      });

      const existing = inventoryLookup.get(key);

      if (existing) {
        // Prepare update
        updatePromises.push(
          this.inventoryRepo.update(existing.id, {
            quantity: existing.quantity + itemRequest.quantity,
            active: true
          })
        );
      } else {
        // Prepare create
        itemsToCreate.push({
          id: "", // Generated by DB
          tenantId,
          cardTemplateId: itemRequest.scryfallId,
          price: itemRequest.price,
          quantity: itemRequest.quantity,
          condition: itemRequest.condition,
          language: itemRequest.language,
          active: true,
          allowNegativeStock: false,
          extras: itemRequest.extras || []
        });
      }

      results.push({
        cardName,
        status: "success"
      });
    }

    // 5. Execute creations and updates
    await Promise.all([
      itemsToCreate.length > 0 ? this.inventoryRepo.createMany(itemsToCreate) : Promise.resolve(),
      ...updatePromises
    ]);

    // 6. Publish event
    domainEvents.publish(DOMAIN_EVENTS.INVENTORY_UPDATED, {
      tenantId,
      cardIds: uniqueScryfallIds,
      source: "bulk_import"
    }).catch((err: unknown) => console.error("Error publishing inventory updated event", err));

    return results;
  }
}
