import { injectable, inject } from "tsyringe";
import { TOKENS } from "../../infrastructure/container";
import type { 
  IInventoryRepository, 
  ICardTemplateRepository 
} from "@/lib/domain/repositories/inventory.repository";
import { scryfall } from "@/lib/scryfall";
import type { ScryfallCard } from "@/lib/types/scryfall";

interface AddInventoryRequest {
  tenantId: string;
  scryfallId: string;
  price: number;
  quantity: number;
  condition: string;
  language: string;
  extras?: string[];
}

@injectable()
export class AddInventoryUseCase {
  constructor(
    @inject(TOKENS.InventoryRepository) private inventoryRepo: IInventoryRepository,
    @inject(TOKENS.CardTemplateRepository) private templateRepo: ICardTemplateRepository
  ) {}

  async execute(request: AddInventoryRequest): Promise<{ success: boolean }> {
    const { 
      tenantId, 
      scryfallId, 
      price, 
      quantity, 
      condition, 
      language, 
      extras = [] 
    } = request;

    // 1. Get or create Card Template
    let template = await this.templateRepo.findById(scryfallId);

    if (!template) {
      const scryfallData = await scryfall.getCardById(scryfallId);
      if (!scryfallData) {
        throw new Error("Card not found in Scryfall");
      }

      const scryfallObj = scryfallData as ScryfallCard;
      const imageUris = scryfallObj.image_uris;

      template = await this.templateRepo.save({
        id: scryfallId,
        name: scryfallData.name,
        set: scryfallData.set.toUpperCase(),
        imageUrl:
          imageUris?.normal ||
          imageUris?.large ||
          imageUris?.png ||
          scryfallObj.card_faces?.[0]?.image_uris?.normal ||
          null,
        backImageUrl:
          scryfallObj.card_faces?.[1]?.image_uris?.normal || null,
        game: "MAGIC",
        metadata: scryfallData as unknown as Record<string, unknown>,
      });
    }

    // 2. Check for existing inventory item
    const existing = await this.inventoryRepo.findByTemplate(tenantId, template.id, {
      price,
      condition,
      language,
      extras,
    });

    if (existing) {
      // Increment quantity
      await this.inventoryRepo.update(existing.id, tenantId, {
        quantity: existing.quantity + quantity,
        active: true,
      });
    } else {
      // Create new inventory item
      await this.inventoryRepo.save({
        id: "", // Will be generated by repo/db
        tenantId,
        cardTemplateId: template.id,
        price,
        quantity,
        condition,
        language,
        active: true,
        extras,
      });
    }

    return { success: true };
  }
}
