import { IOrderRepository } from "@/lib/domain/repositories/order.repository";
import { IInventoryRepository } from "@/lib/domain/repositories/inventory.repository";
import { ICustomerRepository } from "@/lib/domain/repositories/customer.repository";
import { Order, OrderStatus, OrderSource } from "@/lib/domain/entities/order";
import { prisma } from "@/lib/prisma"; // Direct prisma use for transaction orchestration

interface PlaceOrderRequest {
  tenantId: string;
  items: {
    inventoryId: string;
    quantity: number;
    price: number;
  }[];
  customerData: {
    name?: string;
    email?: string;
    phoneNumber: string;
  };
}

export class PlaceOrderUseCase {
  constructor(
    private orderRepo: IOrderRepository,
    private inventoryRepo: IInventoryRepository,
    private customerRepo: ICustomerRepository
  ) {}

  async execute(request: PlaceOrderRequest): Promise<{ orderId: string }> {
    const { tenantId, items, customerData } = request;

    // We use a transaction to ensure atomicity across repositories
    // This is an infrastructure detail leaked into the Use Case for necessity,
    // but we still use the repositories to perform the work.
    const orderId = await prisma.$transaction(async (tx) => {
      // 1. Decrement stock for each item
      for (const item of items) {
        await this.inventoryRepo.decrementStock(item.inventoryId, tenantId, item.quantity);
      }

      // 2. Upsert Customer
      const customer = await this.customerRepo.upsert(customerData.phoneNumber, tenantId, {
        name: customerData.name,
        email: customerData.email,
      });

      // 3. Create Order
      const totalAmount = items.reduce((acc, item) => acc + item.price * item.quantity, 0);

      const orderEntity: Order = {
        id: "", // Generated by repo
        tenantId,
        customerId: customer.id,
        totalAmount,
        status: "PENDING",
        source: "ECOMMERCE",
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const newOrder = await this.orderRepo.save(orderEntity, items.map(item => ({
        inventoryItemId: item.inventoryId,
        quantity: item.quantity,
        priceAtPurchase: item.price,
      })));

      return newOrder.id;
    });

    return { orderId };
  }
}
