import { inject, injectable } from "tsyringe";
import { TOKENS } from "@/lib/infrastructure/container";
import type { IBuylistRepository } from "@/lib/domain/repositories/buylist.repository";
import { BuylistProposal, BuylistStatus } from "@/lib/domain/entities/buylist";
import { IUseCase } from "./use-case.interface";

interface SubmitBuylistProposalRequest {
  tenantId: string;
  customerId: string;
  items: Array<{
    cardTemplateId: string;
    quantity: number;
    condition: string;
    language: string;
    priceCash: number;
    priceCredit: number;
  }>;
}

@injectable()
export class SubmitBuylistProposalUseCase implements IUseCase<SubmitBuylistProposalRequest, BuylistProposal> {
  constructor(
    @inject(TOKENS.BuylistRepository)
    private buylistRepository: IBuylistRepository
  ) {}

  async execute(request: SubmitBuylistProposalRequest): Promise<BuylistProposal> {
    const totalCash = request.items.reduce((acc, item) => acc + (item.priceCash * item.quantity), 0);
    const totalCredit = request.items.reduce((acc, item) => acc + (item.priceCredit * item.quantity), 0);

    const proposal: BuylistProposal = {
      id: "", // Will be generated by DB
      tenantId: request.tenantId,
      customerId: request.customerId,
      status: 'PENDING',
      totalCash,
      totalCredit,
      staffNotes: null,
      items: request.items as any,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return this.buylistRepository.saveProposal(proposal);
  }
}
